name: "My github action"

on: push

jobs:
  initial_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      # - name: "List files"
      #   run: ls
      # - name: "Show readme"
      #   run: cat Readme.md
      - name: Install cowsay
        run: sudo apt-get install cowsay
      - name: "Generate ASCII artwork"
        run: cowsay -f dragon "I am a dragon" > dragon.txt
      - name: "List and read files"
        run: |
          echo "Initial github action"
          ls -ltra
          cat Readme.md

  list_file_job:
    runs-on: ubuntu-latest
    needs: initial_job
    steps:
      - name: sleep
        run: sleep 10
      - name: List the files
        run: ls -ltra

  read_file_job:
    runs-on: ubuntu-latest
    needs: list_file_job
    steps:
      - name: sleep
        run: sleep 15
      - name: read the file
        run: cat dragon.txt
