name: "My github action"

on: push

jobs:
  initial_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Welcome message"
        run: echo "Initial github action"
      - name: "List files"
        run: ls
      - name: "Show readme"
        run: cat Readme.md
