name: "My github action"

on: push

jobs:
  initial_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "List and read files"
        run: |
          echo "Initial github action"
          ls -ltra
          cat Readme.md
      # - name: "List files"
      #   run: ls
      # - name: "Show readme"
      #   run: cat Readme.md
      - name: "Generate ASCII artwork"
        run: cowsay -f dragon "I am a dragon" > dragon.txt
